export default [
  {
    date: 1,
    event: true,
    start: "19:00 PM",
    eventName: "ALPHA",
  },
  {
    date: 2,
    event: true,
    start: "09:00 AM",
    eventName: "BIBLE STUDY",
    secondEvent: true,
    secondEventStart: "18:00 PM",
    secondEventName: "ART CLUB",
  },
  {
    date: 3,
    event: false,
    start: 0,
    eventName: 0,
  },
  {
    date: 4,
    event: false,
    start: 0,
    eventName: 0,
  },
  {
    date: 5,
    event: false,
    start: 0,
    eventName: 0,
  },
  {
    date: 6,
    event: false,
    start: 0,
    eventName: 0,
  },
  {
    date: 7,
    event: false,
    start: 0,
    eventName: 0,
  },
  {
    date: 8,
    event: true,
    start: "19:00 PM",
    eventName: "ALPHA",
  },
  {
    date: 9,
    event: true,
    start: "09:00 AM",
    eventName: "BIBLE STUDY",
  },
  {
    date: 10,
    event: false,
    start: 0,
    eventName: 0,
  },
  {
    date: 11,
    start: "19:00 PM",
    eventName: "TRIVIA NIGHT",
  },
  {
    date: 12,
    event: false,
    start: 0,
    eventName: "",
  },
  {
    date: 13,
    event: false,
    start: 0,
    eventName: 0,
  },
  {
    date: 14,
    event: false,
    start: 0,
    eventName: 0,
  },
  {
    date: 15,
    event: true,
    start: "19:00 PM",
    eventName: "ALPHA",
  },
  {
    date: 16,
    event: true,
    start: "09:00 AM",
    eventName: "BIBLE STUDY",
    secondEvent: true,
    secondEventStart: "15:00 PM",
    secondEventName: "ART CLUB",
  },
  {
    date: 17,
    event: true,
    start: "16:00 PM",
    eventName: "BOOK CLUB",
  },
  {
    date: 18,
    event: true,
    start: "19:00 PM",
    eventName: "OPEN MIC NIGHT",
  },
  {
    date: 19,
    event: false,
    start: 0,
    eventName: 0,
  },
  {
    date: 20,
    event: false,
    start: 0,
    eventName: 0,
  },

  {
    date: 21,
    event: true,
    start: "09:00 AM",
    eventName: "GERMIA - BEAR SANCTUARY HIKE",
  },
  {
    date: 22,
    event: true,
    start: "19:00 PM",
    eventName: "ALPHA",
  },
  {
    date: 23,
    event: true,
    start: "09:00 AM",
    eventName: "BIBLE STUDY",
  },
  {
    date: 24,
    event: true,
    start: "16:00 PM",
    eventName: "BOOK CLUB",
  },
  {
    date: 25,
    event: true,
    start: "19:00 PM",
    eventName: "TRIVIA NIGHT",
  },
  {
    date: 26,
    event: false,

    start: 0,
    eventName: 0,
  },
  {
    date: 27,
    event: true,
    start: "19:00 PM",
    eventName: "WORSHIP NIGHT",
  },
  {
    date: 28,
    event: false,
    start: 0,
    eventName: 0,
  },
  {
    date: 29,
    event: true,
    start: "19:00 PM",
    eventName: "ALPHA",
  },
  {
    date: 30,
    event: true,
    start: "09:00 AM",
    eventName: "BIBLE STUDY",
    secondEvent: true,
    secondEventStart: "13:00",
    secondEventName: "ART CLUB",
  },
];
